baseURL = "https://baja.co.id"
languageCode = "id-ID"
title = "Distributor Produk Besi/Baja Indonesia. Atap Baja Ringan, Plat Baja, Besi Beton, Wiremesh, Besi Kanal, Besi Hollow, Dll"
assetDir = "static"
